config:
   version: 1
   id: GATEWAY-IG-000000001
   desc: InModbus configuration
   mode: mqtt # mqtt/transform
   others:
      LOG:
        #Enable debug feature to write all logs to the console
        #Default: debug=0
        debug: 1
      REMOTE: 
         host: '192.168.2.24'
         port: 1883
         username: ipLSqIcoW87YReQerBB4
         topic: v1/devices/me/telemetry
         #passwd: ''
         #tls:
         #capath:   
devices:
   - id: EliwellOne
     protocol: mbrtu
     address: 10.5.16.191
     param: 9600-8-N-1
     port: /dev/ttyO3
     machine_address: '1'
     byte_order: cdab
     groups:
       - name: 123
         interval: 10
         read_backoff: 0.5
         vars:
           - id: Temperature
             address: '40001'
             type: word
             desc: A Set point 1
             expression:  "gd/10.0"
             writeable: false
           - id: Humidity
             address: '40012'
             type: word
             desc: A Set point 2
             expression:  "gd/10.0"
             writeable: false


